import type { Issue, Employee, JurisdictionZone } from "./types"

export const employees: Employee[] = [
  { id: "emp-1", name: "Priya Sharma", role: "Field Inspector", avatar: "/avatars/priya.jpg" },
  { id: "emp-2", name: "Rajesh Patel", role: "Maintenance Lead", avatar: "/avatars/rajesh.jpg" },
  { id: "emp-3", name: "Ananya Desai", role: "Infrastructure Engineer", avatar: "/avatars/ananya.jpg" },
]

export const issues: Issue[] = [
  // Potholes
  {
    id: "ISS-001",
    title: "Major Pothole - Traffic Hazard",
    location: "Linking Road, Bandra West",
    coordinates: { lat: 19.0596, lng: 72.8295 },
    healthScore: 23,
    riskLevel: "critical",
    status: "open",
    assignedTo: null,
    aiInsight: "Pothole depth exceeds 15cm. High traffic volume increases accident risk. Immediate repair required to prevent vehicle damage and liability.",
    reportedAt: "2026-02-03T08:30:00Z",
    imageUrl: "/issues/pothole-1.jpg",
    category: "pothole",
  },
  {
    id: "ISS-007",
    title: "Deep Pothole Near School Zone",
    location: "Juhu Tara Road - School Area",
    coordinates: { lat: 19.0883, lng: 72.8262 },
    healthScore: 31,
    riskLevel: "critical",
    status: "open",
    assignedTo: null,
    aiInsight: "Located in active school zone. Risk of cyclist injuries elevated. Prioritize repair before school hours resume.",
    reportedAt: "2026-02-03T07:15:00Z",
    imageUrl: "/issues/pothole-2.jpg",
    category: "pothole",
  },
  {
    id: "ISS-008",
    title: "Surface Deterioration - Multiple Potholes",
    location: "SV Road, Andheri West",
    coordinates: { lat: 19.1197, lng: 72.8464 },
    healthScore: 45,
    riskLevel: "medium",
    status: "assigned",
    assignedTo: "emp-1",
    aiInsight: "Cluster of 4 potholes in 50m stretch. Subsurface drainage issue suspected. Recommend comprehensive road assessment.",
    reportedAt: "2026-02-02T11:20:00Z",
    imageUrl: "/issues/pothole-3.jpg",
    category: "pothole",
  },
  // Bridges
  {
    id: "ISS-002",
    title: "Bridge Joint Expansion Failure",
    location: "Bandra-Worli Sea Link - Section C",
    coordinates: { lat: 19.0380, lng: 72.8168 },
    healthScore: 38,
    riskLevel: "high",
    status: "assigned",
    assignedTo: "emp-3",
    aiInsight: "Thermal expansion joints showing 67% wear. Load distribution compromised. Schedule repair within 30 days to maintain structural integrity.",
    reportedAt: "2026-02-02T14:15:00Z",
    imageUrl: "/issues/bridge-joint-1.jpg",
    category: "bridge",
  },
  {
    id: "ISS-009",
    title: "Bridge Deck Corrosion Detected",
    location: "Mahim Causeway - North Span",
    coordinates: { lat: 19.0425, lng: 72.8396 },
    healthScore: 52,
    riskLevel: "medium",
    status: "open",
    assignedTo: null,
    aiInsight: "Surface corrosion at 23% coverage. Structural integrity maintained but deterioration accelerating. Schedule protective coating application.",
    reportedAt: "2026-02-01T09:30:00Z",
    imageUrl: "/issues/bridge-2.jpg",
    category: "bridge",
  },
  {
    id: "ISS-010",
    title: "Pedestrian Overpass Railing Damage",
    location: "Dadar Station Skywalk",
    coordinates: { lat: 19.0195, lng: 72.8427 },
    healthScore: 61,
    riskLevel: "low",
    status: "open",
    assignedTo: null,
    aiInsight: "Impact damage to railing section. Safety barrier compromised. Non-urgent but requires attention for pedestrian safety compliance.",
    reportedAt: "2026-01-30T15:45:00Z",
    imageUrl: "/issues/bridge-3.jpg",
    category: "bridge",
  },
  // Water Leakages
  {
    id: "ISS-003",
    title: "Water Main Pressure Anomaly",
    location: "MIDC Industrial Area, Andheri East",
    coordinates: { lat: 19.1136, lng: 72.8697 },
    healthScore: 42,
    riskLevel: "high",
    status: "in-progress",
    assignedTo: "emp-2",
    aiInsight: "Pressure readings 23% below normal. Pattern suggests significant leak. Estimated water loss: 2000 litres/day. Underground excavation required.",
    reportedAt: "2026-02-01T11:00:00Z",
    imageUrl: "/issues/water-main-1.jpg",
    category: "water-leakage",
  },
  {
    id: "ISS-011",
    title: "Fire Hydrant Leak - Continuous Flow",
    location: "Crawford Market, Fort",
    coordinates: { lat: 18.9472, lng: 72.8328 },
    healthScore: 35,
    riskLevel: "high",
    status: "open",
    assignedTo: null,
    aiInsight: "Hydrant valve seal failure. Continuous water loss creating road hazard and slipping risk. Fire safety capacity reduced in area.",
    reportedAt: "2026-02-03T06:00:00Z",
    imageUrl: "/issues/hydrant-1.jpg",
    category: "water-leakage",
  },
  {
    id: "ISS-012",
    title: "Storm Drain Overflow",
    location: "Hindmata, Parel - Low Point",
    coordinates: { lat: 19.0072, lng: 72.8432 },
    healthScore: 55,
    riskLevel: "medium",
    status: "open",
    assignedTo: null,
    aiInsight: "Drainage capacity exceeded during moderate rainfall. Blockage suspected. Risk of road flooding during next monsoon event.",
    reportedAt: "2026-02-02T18:30:00Z",
    imageUrl: "/issues/drain-1.jpg",
    category: "water-leakage",
  },
  // Infrastructure
  {
    id: "ISS-004",
    title: "Street Light Foundation Erosion",
    location: "Marine Drive - Near Chowpatty",
    coordinates: { lat: 18.9548, lng: 72.8134 },
    healthScore: 41,
    riskLevel: "high",
    status: "open",
    assignedTo: null,
    aiInsight: "Foundation erosion detected at 45% depth. Risk of toppling in high winds. Recommend immediate stabilization to prevent public safety hazard.",
    reportedAt: "2026-01-30T09:45:00Z",
    imageUrl: "/issues/light-post-1.jpg",
    category: "infrastructure",
  },
  {
    id: "ISS-005",
    title: "Traffic Signal Malfunction",
    location: "Haji Ali Junction",
    coordinates: { lat: 18.9827, lng: 72.8120 },
    healthScore: 28,
    riskLevel: "critical",
    status: "assigned",
    assignedTo: "emp-1",
    aiInsight: "Signal timing erratic. Red-green cycle inconsistent creating dangerous intersection conditions. Traffic police deployed temporarily.",
    reportedAt: "2026-02-03T16:20:00Z",
    imageUrl: "/issues/signal-1.jpg",
    category: "infrastructure",
  },
  {
    id: "ISS-006",
    title: "Sidewalk Accessibility Ramp Damage",
    location: "BMC Headquarters, CST",
    coordinates: { lat: 18.9398, lng: 72.8355 },
    healthScore: 68,
    riskLevel: "low",
    status: "resolved",
    assignedTo: "emp-1",
    aiInsight: "Accessibility ramp surface cracking. Compliance concern for PwD standards. Include in next scheduled maintenance window.",
    reportedAt: "2026-01-28T13:30:00Z",
    imageUrl: "/issues/ramp-1.jpg",
    category: "infrastructure",
  },
  {
    id: "ISS-013",
    title: "Guardrail Collision Damage",
    location: "Western Express Highway, Goregaon",
    coordinates: { lat: 19.1663, lng: 72.8526 },
    healthScore: 47,
    riskLevel: "medium",
    status: "open",
    assignedTo: null,
    aiInsight: "30-meter section of guardrail deformed from vehicle impact. Barrier effectiveness reduced by 60%. Priority repair for highway safety.",
    reportedAt: "2026-02-01T22:15:00Z",
    imageUrl: "/issues/guardrail-1.jpg",
    category: "infrastructure",
  },
]

export const jurisdictionZones: JurisdictionZone[] = [
  {
    id: "zone-mumbai",
    name: "Greater Mumbai",
    bounds: [
      { lat: 18.83, lng: 72.77 },
      { lat: 19.35, lng: 72.77 },
      { lat: 19.35, lng: 72.99 },
      { lat: 18.83, lng: 72.99 },
    ],
    issueCount: 0,
    avgHealthScore: 0,
  },
]
